### ISSUE TITLE
Set body { background-color: #fff; }

### ISSUE THREAD

**Issue by jplatte** [integer32llc/website#3]
Not everyone has the black text on white background as the default in their browser, so if you set the text color it would be good to also set the background-color. Otherwise this can happen:
![bildschirmfoto am 2016-07-21 um 15 40 11](https://cloud.githubusercontent.com/assets/951129/17024788/800ad500-4f59-11e6-883f-270b4ab29c7a.png)

**Comment by carols10cents** [comment]
Eeeeeeeewwww. Thank you for letting us know, I'll fix it soon! ❤️

**Comment by carols10cents** [comment]
Should be fixed now-- let me know if it isn't. Thank you for the bug report!!
